name: pawurelove
description: "PawureLove - Loving care for your furry best friend"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  fl_chart: ^0.70.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  flutter_timezone: ^5.0.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  file_saver: ^0.3.1
  image_cropper: ^12.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/logo.png"
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#F9F9F9"
  image: "assets/logo.png"
  android_12:
    image: "assets/logo.png"
    color: "#F9F9F9"
